<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Курс доллара к текущей валюте сегодня = ${todayValue} - это больше, чем вчера на ${difference}</h3>
<iframe src="${embed_url}" width="480" height="318" frameBorder="0" class="giphy-embed"
        allowFullScreen></iframe>
<p><a href="/v1/welcome">Вернуться на главную страницу</a></p>
</body>
</html>